### ISSUE TITLE
Could not find process injector before 10 sec

### ISSUE THREAD

**Issue by workdowg** [ori-rando/build#3]
Windows 11... It doesn't wait long enough for injector to start. It starts about 20 seconds later. I'm sure it's Windows 11 doing it slow.

Any way to lengthen the time until Windows 11 is fixed? A lot of programs take longer to start...

BTW...
Windows 11 Pro - Devel Preview
Intel i11700, Aorus Elite AX, 32GB Corsair ram,
 Samsung EVO-Pro 1TB NvMe, MSI RTX2070 Super

**Comment by timoschwarzer** [comment]
It sounds like your antivirus sandboxes the injector. The injector itself does not need more than 10 seconds to start. Please add an exception for Injector.exe in the rando directory.

**Comment by workdowg** [comment]
Actually everything that requires UAC takes a long time to load. This is definitely a Windows 11 issue. Closing.

**Comment by timoschwarzer** [comment]
@workdowg Hmm, I'm running Windows 11, too, and it starts instantly. Did it work for you after deactivating your antivirus temporarily?
